name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "ap-southeast-2  # Change to your AWS region

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js  # Change to Java/Python/etc. as needed
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install  # Or pip install, mvn install, etc.

    - name: Run tests
      run: npm test  # Replace with your test command

  deploy:
    needs: test  # Only run if tests pass
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build application  # Customize for your stack
      run: npm run build  # Or ./gradlew build, etc.

    - name: Deploy to AWS
      run: |
        # Add your deployment commands here, for example:
        aws s3 sync ./dist s3://your-bucket-name
        # Or AWS Elastic Beanstalk/ECS/Lambda deployment
